---
title: "Twitter Users Analysis"
author: "Salil Gupta"
date: "May 3, 2019"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::opts_chunk$set(fig.width=12, fig.height=12)
```

## Twitter Analysis Report

This report is for two of the organization's Twitter friends:

American Red Cross @RedCross, American Association of Nurse Practitioners




```{r echo = FALSE, warning = FALSE, message = FALSE}
rm(list=ls())


library(dplyr)
library(tibble)
library(tidytext)
library(stringr)
library(ggplot2)
library(tidyr)
library(lubridate)
library(ggplot2)
library(dplyr)
library(readr)
library(tidyverse)
library(purrr)
library(broom)
library(data.table)
```

```{r echo = FALSE, warning = FALSE, message = FALSE}
tf_Tweeter <- fread("C://Users//lilas//UserAANP_News.txt", header = FALSE, sep = '|', skip = 1)

colnames(tf_Tweeter) <- c("text", "timestamp", "tweetid", "userid")

tf_Tweeter$cleantext <- gsub('[[:punct:] ]+',' ', substring(tf_Tweeter$text,2))

tib_Tweeter <- tibble(text = tf_Tweeter$cleantext, line = 1:3000)

tib_Tweeter <- tib_Tweeter %>%
  unnest_tokens( word,  text)

tidy_Tweeter <- tib_Tweeter %>% anti_join(stop_words)  %>% filter(word != "brt")
##tidy_Tweeter




tf_TweeterB <- fread("C://Users//lilas//UserRedCross.txt", header = FALSE, sep = '|', skip = 1)


colnames(tf_TweeterB) <- c("text", "timestamp", "tweetid", "userid")

tf_TweeterB$cleantext <- gsub('[[:punct:] ]+',' ', substring(tf_TweeterB$text,2))



tib_TweeterB <- tibble(text = tf_TweeterB$cleantext, line = 1:3000)

tib_TweeterB <- tib_TweeterB %>%
  unnest_tokens( word,  text)

tidy_TweeterB <- tib_TweeterB %>% anti_join(stop_words)  %>% filter(word != "brt")
##tidy_TweeterB
```









```{r echo = FALSE, warning = FALSE, message = FALSE}
tweets <- bind_rows(tf_TweeterB %>% 
                      mutate(person = "RedCross"),
                    tf_Tweeter %>% 
                      mutate(person = "AANP_News")) %>%
  mutate(timestamp = ymd_hms(timestamp))

remove_reg <- "&amp;|&lt;|&gt;"
tidy_tweets <- tweets %>% 
  filter(!str_detect(text, "^RT")) %>%
  
  mutate(text = str_remove_all(text, remove_reg)) %>%
  unnest_tokens(word, text, token = "tweets") %>%
  filter(!word %in% stop_words$word,
         !word %in% str_remove_all(stop_words$word, "'"),
         str_detect(word, "[a-z]")) %>%
  filter(word != "brt") %>%
  filter(word != "bthe") %>%
  filter(!grepl("\\d", word))






ggplot(tweets, aes(x = timestamp, fill = person)) +
  geom_histogram(position = "identity", bins = 20, show.legend = FALSE) +
  facet_wrap(~person, ncol = 1)
```






```{r echo = FALSE, warning = FALSE, message = FALSE}
library(wordcloud)

pal <- brewer.pal(8,"Dark2")



wordclouddata_a <- tidy_tweets %>% filter(person == 'AANP_News')
wordcloud(wordclouddata_a$word, random.order = FALSE, max.words = 50, colors=pal, main = '@AANP_News')
```




```{r echo = FALSE, warning = FALSE, message = FALSE}

library(wordcloud)

pal <- brewer.pal(8,"Dark2")



wordclouddata_b <- tidy_tweets %>% filter(person == 'RedCross')
wordcloud(wordclouddata_b$word, random.order = FALSE, max.words = 50, colors=pal, main = '@RedCross')


```


```{r echo = FALSE, warning = FALSE, message = FALSE}
bing_word_counts <- tidy_Tweeter %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) %>%
  ungroup()

##bing_word_counts



nrc_joy <- get_sentiments("nrc") %>% 
  filter(sentiment == "joy")



bing_word_countsB <- tidy_TweeterB %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) %>%
  ungroup()



```



```{r echo = FALSE, warning = FALSE, message = FALSE}
bing_word_counts %>%
  group_by(sentiment) %>%
  top_n(10) %>%
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(y = "AANP News Sentiment +-",
       x = NULL) +
  coord_flip()



```






```{r echo = FALSE, warning = FALSE, message = FALSE}
bing_word_countsB %>%
  group_by(sentiment) %>%
  top_n(10) %>%
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(y = "RedCross Sentiment +-",
       x = NULL) +
  coord_flip()



```















```{r echo = FALSE, warning = FALSE, message = FALSE}



frequency <- tidy_tweets %>% 
  group_by(person) %>% 
  count(word, sort = TRUE) %>% 
  left_join(tidy_tweets %>% 
              group_by(person) %>% 
              summarise(total = n())) %>%
  mutate(freq = n/total)

##frequency
```

```{r echo = FALSE, warning = FALSE, message = FALSE}

word_ratios <- tidy_tweets %>%
  filter(!str_detect(word, "^@")) %>%
  count(word, person) %>%
  group_by(word) %>%
  filter(sum(n) >= 10) %>%
  ungroup() %>%
  spread(person, n, fill = 0) %>%
  mutate_if(is.numeric, funs((. + 1) / (sum(.) + 1))) %>%
  mutate(logratio = log(AANP_News / RedCross)) %>%
  arrange(desc(logratio))


word_ratios %>%
  group_by(logratio < 0) %>%
  top_n(15, abs(logratio)) %>%
  ungroup() %>%
  mutate(word = reorder(word, logratio)) %>%
  ggplot(aes(word, logratio, fill = logratio < 0)) +
  geom_col(show.legend = FALSE) +
  coord_flip() +
  ylab("log odds ratio (AANP News/RedCross)") +
  scale_fill_discrete(name = "", labels = c("AANP News", "Red Cross"))

```













```{r echo = FALSE, warning = FALSE, message = FALSE}

words_by_time <- tidy_tweets %>%
  filter(word != "brt") %>%
  filter(!str_detect(word, "^@")) %>%
  mutate(time_floor = floor_date(timestamp, unit = "1 month")) %>%
  count(time_floor, person, word) %>%
  group_by(person, time_floor) %>%
  mutate(time_total = sum(n)) %>%
  group_by(person, word) %>%
  mutate(word_total = sum(n)) %>%
  ungroup() %>%
  rename(count = n) %>%
  filter(word_total > 30)

##words_by_time



nested_data <- words_by_time %>%
  nest(-word, -person) 

##nested_data


nested_models <- nested_data %>%
  mutate(models = map(data, ~ glm(cbind(count, time_total) ~ time_floor, ., 
                                  family = "binomial")))

##nested_models


slopes <- nested_models %>%
  unnest(map(models, tidy)) %>%
  filter(term == "time_floor") %>%
  mutate(adjusted.p.value = p.adjust(p.value))




top_slopes <- slopes %>% 
  filter(adjusted.p.value < 0.05)

##top_slopes










words_by_time %>%
  inner_join(top_slopes, by = c("word", "person")) %>%
  filter(person == "RedCross") %>%
  ggplot(aes(time_floor, count/time_total, color = word)) +
  geom_line(size = 1.3) +
  labs(x = 'RedCross', y = "Word frequency")
```








```{r echo = FALSE, warning = FALSE, message = FALSE}
words_by_time %>%
  inner_join(top_slopes, by = c("word", "person")) %>%
  filter(person == "AANP_News") %>%
  ggplot(aes(time_floor, count/time_total, color = word)) +
  geom_line(size = 1.3) +
  labs(x = 'AANP News', y = "Word frequency")

```






